name: The British Pilot in New Zealand
favicon: null
layout_spectrum: 0.47284
typography_spectrum: 0.89105
title: The British Pilot in NZ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0807'
    - '#4a5569'
    - '#b2b6b5'
    - '#ffffff'
    - '#d9571d'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
