name: The British Pilot in New Zealand
favicon: null
layout_spectrum: 0.418488210067153
typography_spectrum: 0.5517806229181588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5836046496406198
  lightness: 0.5121846413239837
  saturation: 0.7031058217398822
  rhythmicContrast: 0.9344208447728306
purpose: []
